declare module 'lucide-react' {
  import { ComponentType, SVGProps } from 'react'
  export const GraduationCap: ComponentType<SVGProps<SVGSVGElement>>
  export const Users: ComponentType<SVGProps<SVGSVGElement>>
  export const Building2: ComponentType<SVGProps<SVGSVGElement>>
  export const CalendarCheck: ComponentType<SVGProps<SVGSVGElement>>
  export const IndianRupee: ComponentType<SVGProps<SVGSVGElement>>
  export const Award: ComponentType<SVGProps<SVGSVGElement>>
  export const BarChart3: ComponentType<SVGProps<SVGSVGElement>>
  export const UserCog: ComponentType<SVGProps<SVGSVGElement>>
  export const Settings: ComponentType<SVGProps<SVGSVGElement>>
  export const LayoutDashboard: ComponentType<SVGProps<SVGSVGElement>>
  export const Menu: ComponentType<SVGProps<SVGSVGElement>>
  export const X: ComponentType<SVGProps<SVGSVGElement>>
  export const LogOut: ComponentType<SVGProps<SVGSVGElement>>
  export const ChevronDown: ComponentType<SVGProps<SVGSVGElement>>
  export const Bell: ComponentType<SVGProps<SVGSVGElement>>
  export const Eye: ComponentType<SVGProps<SVGSVGElement>>
  export const EyeOff: ComponentType<SVGProps<SVGSVGElement>>
  export const Lock: ComponentType<SVGProps<SVGSVGElement>>
  export const User: ComponentType<SVGProps<SVGSVGElement>>
  export const Mail: ComponentType<SVGProps<SVGSVGElement>>
  export const Search: ComponentType<SVGProps<SVGSVGElement>>
  export const Plus: ComponentType<SVGProps<SVGSVGElement>>
  export const Edit: ComponentType<SVGProps<SVGSVGElement>>
  export const Trash2: ComponentType<SVGProps<SVGSVGElement>>
  export const ChevronLeft: ComponentType<SVGProps<SVGSVGElement>>
  export const ChevronRight: ComponentType<SVGProps<SVGSVGElement>>
  export const Filter: ComponentType<SVGProps<SVGSVGElement>>
  export const Download: ComponentType<SVGProps<SVGSVGElement>>
  export const Upload: ComponentType<SVGProps<SVGSVGElement>>
  export const AlertCircle: ComponentType<SVGProps<SVGSVGElement>>
  export const Check: ComponentType<SVGProps<SVGSVGElement>>
  export const Loader2: ComponentType<SVGProps<SVGSVGElement>>
  export const RefreshCw: ComponentType<SVGProps<SVGSVGElement>>
  export const Save: ComponentType<SVGProps<SVGSVGElement>>
  export const MoreHorizontal: ComponentType<SVGProps<SVGSVGElement>>
  export const ChevronUp: ComponentType<SVGProps<SVGSVGElement>>
  export const ArrowUpDown: ComponentType<SVGProps<SVGSVGElement>>
  export const Phone: ComponentType<SVGProps<SVGSVGElement>>
  export const Calendar: ComponentType<SVGProps<SVGSVGElement>>
  export const DollarSign: ComponentType<SVGProps<SVGSVGElement>>
  export const FileText: ComponentType<SVGProps<SVGSVGElement>>
  export const Copy: ComponentType<SVGProps<SVGSVGElement>>
  export const ExternalLink: ComponentType<SVGProps<SVGSVGElement>>
  export const Home: ComponentType<SVGProps<SVGSVGElement>>
  export const Clock: ComponentType<SVGProps<SVGSVGElement>>
  export const TrendingUp: ComponentType<SVGProps<SVGSVGElement>>
  export const BookOpen: ComponentType<SVGProps<SVGSVGElement>>
  export const Shield: ComponentType<SVGProps<SVGSVGElement>>
  export const PieChart: ComponentType<SVGProps<SVGSVGElement>>
  export const Activity: ComponentType<SVGProps<SVGSVGElement>>
  export const Star: ComponentType<SVGProps<SVGSVGElement>>
  export const Inbox: ComponentType<SVGProps<SVGSVGElement>>
  export const AlertTriangle: ComponentType<SVGProps<SVGSVGElement>>
  export const CheckCircle: ComponentType<SVGProps<SVGSVGElement>>
  export const XCircle: ComponentType<SVGProps<SVGSVGElement>>
  export const Info: ComponentType<SVGProps<SVGSVGElement>>
  export const Minus: ComponentType<SVGProps<SVGSVGElement>>
  export const Maximize2: ComponentType<SVGProps<SVGSVGElement>>
  export const MapPin: ComponentType<SVGProps<SVGSVGElement>>
  export const Briefcase: ComponentType<SVGProps<SVGSVGElement>>
  export const Layers: ComponentType<SVGProps<SVGSVGElement>>
  export const Grid: ComponentType<SVGProps<SVGSVGElement>>
  export const List: ComponentType<SVGProps<SVGSVGElement>>
  export const ToggleLeft: ComponentType<SVGProps<SVGSVGElement>>
  export const ToggleRight: ComponentType<SVGProps<SVGSVGElement>>
  export const Key: ComponentType<SVGProps<SVGSVGElement>>
  export const Camera: ComponentType<SVGProps<SVGSVGElement>>
  export const CreditCard: ComponentType<SVGProps<SVGSVGElement>>
  export const Wallet: ComponentType<SVGProps<SVGSVGElement>>
  export const CircleDot: ComponentType<SVGProps<SVGSVGElement>>
  export const Hash: ComponentType<SVGProps<SVGSVGElement>>
  export const ChevronsUpDown: ComponentType<SVGProps<SVGSVGElement>>
  export const CheckCircle2: ComponentType<SVGProps<SVGSVGElement>>
  export const TrendingDown: ComponentType<SVGProps<SVGSVGElement>>
  export const ArrowUpRight: ComponentType<SVGProps<SVGSVGElement>>
  export const Pencil: ComponentType<SVGProps<SVGSVGElement>>
  export type LucideIcon = ComponentType<SVGProps<SVGSVGElement>>
}
